# Prusa MINI(+)

[printer]
bed_mesh = true
axis_minimum = [0, 0, 0]
axis_maximum = [180, 180, 180]

[printer.extruder]
min_temp = 0
max_temp = 280
min_extrude_temp = 180
filament_diameter = 1.75

[printer.heater_bed]
min_temp = 0
max_temp = 100

[printer.gcode]
send_m73 = false
report_velocity = false
