# Prusa i3 MK3S(+)

[printer]
bed_mesh = true
axis_minimum = [0, 0, 0]
axis_maximum = [210, 210, 250]

[printer.extruder]
min_temp = 0
max_temp = 300
min_extrude_temp = 180
filament_diameter = 1.75

[printer.heater_bed]
min_temp = 0
max_temp = 120

[printer.gcode]
send_m73 = false
report_velocity = true
