#<include printer.toml>

[web]
port = 7125
cors_domains = []

[serial]
port = "auto"
baud_rate = "auto"
max_connection_attempts = 5
connection_timeout = 5000

[misc]
octoprint_compat = true
extended_logs = false
allowed_services = ["marlinraker", "crowsnest", "MoonCord",
    "moonraker-telegram-bot", "KlipperScreen", "sonar", "webcamd"]

[macros.pause]
rename_exising = "pause_base"
gcode = """
  PAUSE_BASE
  SAVE_GCODE_STATE NAME=print_pause
  _PARK_TOOLHEAD
"""

[macros.resume]
rename_existing = "resume_base"
gcode = """
  RESTORE_GCODE_STATE NAME=print_pause
  RESUME_BASE
"""

[macros.cancel_print]
rename_exising = "cancel_print_base"
gcode = """
  CANCEL_PRINT_BASE
  _PARK_TOOLHEAD
"""

[macros._park_toolhead]
gcode = """
  G91
  G1 Z5 E-1 F900
  G90
  G1 X0 Y0 F2500
  TURN_OFF_HEATERS
"""
