name: Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: 2.x
          args: release --clean --snapshot

      - uses: actions/upload-artifact@v4
        with:
          name: marlinraker_snapshot_artifacts
          path: dist/marlinraker_*/marlinraker
